#ifndef ARCADE_INPUTQKEYPRESSEDEVENT_HPP
#define ARCADE_INPUTQKEYPRESSEDEVENT_HPP
#include "../../Shared_Abstracts/AInputArcadeEvent.hpp"

namespace arc {
    /**
     * @class InputQKeyPressedEvent
     * @brief Event triggered when the Q key is pressed.
     *
     * This event is generated by the display module when the user presses
     * the Q key. Typically used as a quick exit or quit command in games.
     */
    class InputQKeyPressedEvent: public AInputArcadeEvent {
    public:
        /**
         * @brief Default constructor.
         */
        InputQKeyPressedEvent()  = default;

        /**
         * @brief Virtual destructor for proper cleanup.
         */
        ~InputQKeyPressedEvent() override = default;
    };
} // arc

#endif //ARCADE_INPUTQKEYPRESSEDEVENT_HPP
