//
// Created by user on 3/24/26.
//

#ifndef ARCADE_INPUTUPARROWKEYPRESSEDEVENT_HPP
#define ARCADE_INPUTUPARROWKEYPRESSEDEVENT_HPP
#include "../../Shared_Abstracts/AInputArcadeEvent.hpp"

namespace arc {
    /**
     * @class InputUpArrowKeyPressedEvent
     * @brief Event triggered when the up arrow key is pressed.
     *
     * This event is generated by the display module when the user presses
     * the up arrow key. Typically used for menu navigation or character movement.
     */
    class InputUpArrowKeyPressedEvent: public AInputArcadeEvent {
    public:
        /**
         * @brief Default constructor.
         */
        InputUpArrowKeyPressedEvent()  = default;

        /**
         * @brief Virtual destructor for proper cleanup.
         */
        ~InputUpArrowKeyPressedEvent() override = default;
    };
} // arc

#endif //ARCADE_INPUTUPARROWKEYPRESSEDEVENT_HPP