#ifndef ARCADE_INPUTNUMPAD2KEYPRESSEDEVENT_HPP
#define ARCADE_INPUTNUMPAD2KEYPRESSEDEVENT_HPP
#include "../../Shared_Abstracts/AInputArcadeEvent.hpp"

namespace arc {
    /**
     * @class InputNumpad2KeyPressedEvent
     * @brief Event triggered when the Numpad 2 key is pressed.
     *
     * This event is generated by the display module when the user presses
     * the 2 key on the numeric keypad. Typically used for quick selection
     * or hotkey activation in games.
     */
    class InputNumpad2KeyPressedEvent: public AInputArcadeEvent {
    public:
        /**
         * @brief Default constructor.
         */
        InputNumpad2KeyPressedEvent()  = default;

        /**
         * @brief Virtual destructor for proper cleanup.
         */
        ~InputNumpad2KeyPressedEvent() override = default;
    };
} // arc

#endif //ARCADE_INPUTNUMPAD2KEYPRESSEDEVENT_HPP
