#ifndef ARCADE_INPUTNUMPAD3KEYPRESSEDEVENT_HPP
#define ARCADE_INPUTNUMPAD3KEYPRESSEDEVENT_HPP
#include "../../Shared_Abstracts/AInputArcadeEvent.hpp"

namespace arc {
    /**
     * @class InputNumpad3KeyPressedEvent
     * @brief Event triggered when the Numpad 3 key is pressed.
     *
     * This event is generated by the display module when the user presses
     * the 3 key on the numeric keypad. Typically used for quick selection
     * or hotkey activation in games.
     */
    class InputNumpad3KeyPressedEvent: public AInputArcadeEvent {
    public:
        /**
         * @brief Default constructor.
         */
        InputNumpad3KeyPressedEvent()  = default;

        /**
         * @brief Virtual destructor for proper cleanup.
         */
        ~InputNumpad3KeyPressedEvent() override = default;
    };
} // arc

#endif //ARCADE_INPUTNUMPAD3KEYPRESSEDEVENT_HPP
