//
// Created by user on 3/19/26.
//

#ifndef ARCADE_INPUTRIGHTARROWKEYPRESSEDEVENT_HPP
#define ARCADE_INPUTRIGHTARROWKEYPRESSEDEVENT_HPP
#include "../../Shared_Abstracts/AInputArcadeEvent.hpp"

namespace arc {
    /**
     * @class InputRightArrowKeyPressedEvent
     * @brief Event triggered when the right arrow key is pressed.
     *
     * This event is generated by the display module when the user presses
     * the right arrow key. Typically used for menu navigation or character movement.
     */
    class InputRightArrowKeyPressedEvent: public AInputArcadeEvent {
    public:
        /**
         * @brief Default constructor.
         */
        InputRightArrowKeyPressedEvent()  = default;

        /**
         * @brief Virtual destructor for proper cleanup.
         */
        ~InputRightArrowKeyPressedEvent()  override = default;
    };
} // arc

#endif //ARCADE_INPUTRIGHTARROWKEYPRESSEDEVENT_HPP