//
// Created by user on 3/24/26.
//

#ifndef ARCADE_INPUTDOWNARROWKEYPRESSEDEVENT_HPP
#define ARCADE_INPUTDOWNARROWKEYPRESSEDEVENT_HPP
#include "../../Shared_Abstracts/AInputArcadeEvent.hpp"

namespace arc {
    /**
     * @class InputDownArrowKeyPressedEvent
     * @brief Event triggered when the down arrow key is pressed.
     *
     * This event is generated by the display module when the user presses
     * the down arrow key. Typically used for menu navigation or character movement.
     */
    class InputDownArrowKeyPressedEvent: public AInputArcadeEvent {
    public:
        /**
         * @brief Default constructor.
         */
        InputDownArrowKeyPressedEvent()  = default;

        /**
         * @brief Virtual destructor for proper cleanup.
         */
        ~InputDownArrowKeyPressedEvent() override = default;
    };
} // arc

#endif //ARCADE_INPUTDOWNARROWKEYPRESSEDEVENT_HPP