#ifndef ARCADE_INPUTNUMPAD1KEYPRESSEDEVENT_HPP
#define ARCADE_INPUTNUMPAD1KEYPRESSEDEVENT_HPP
#include "../../Shared_Abstracts/AInputArcadeEvent.hpp"

namespace arc {
    /**
     * @class InputNumpad1KeyPressedEvent
     * @brief Event triggered when the Numpad 1 key is pressed.
     *
     * This event is generated by the display module when the user presses
     * the 1 key on the numeric keypad. Typically used for quick selection
     * or hotkey activation in games.
     */
    class InputNumpad1KeyPressedEvent: public AInputArcadeEvent {
    public:
        /**
         * @brief Default constructor.
         */
        InputNumpad1KeyPressedEvent()  = default;

        /**
         * @brief Virtual destructor for proper cleanup.
         */
        ~InputNumpad1KeyPressedEvent() override = default;
    };
} // arc

#endif //ARCADE_INPUTNUMPAD1KEYPRESSEDEVENT_HPP
