//
// Created by user on 3/24/26.
//

#ifndef ARCADE_INPUTLEFTARROWKEYPRESSEDEVENT_HPP
#define ARCADE_INPUTLEFTARROWKEYPRESSEDEVENT_HPP
#include "../../Shared_Abstracts/AInputArcadeEvent.hpp"

namespace arc {
    /**
     * @class InputLeftArrowKeyPressedEvent
     * @brief Event triggered when the left arrow key is pressed.
     *
     * This event is generated by the display module when the user presses
     * the left arrow key. Typically used for menu navigation or character movement.
     */
    class InputLeftArrowKeyPressedEvent : public AInputArcadeEvent {
    public:
        /**
         * @brief Default constructor.
         */
        InputLeftArrowKeyPressedEvent()  = default;

        /**
         * @brief Virtual destructor for proper cleanup.
         */
        ~InputLeftArrowKeyPressedEvent() override = default;
    };
} // arc

#endif //ARCADE_INPUTLEFTARROWKEYPRESSEDEVENT_HPP