//
// Created by user on 4/7/26.
//

#ifndef ARCADE_INPUTRKEYPRESSEDEVENT_HPP
#define ARCADE_INPUTRKEYPRESSEDEVENT_HPP

#include "../../Shared_Abstracts/AInputArcadeEvent.hpp"

namespace arc {
    /**
     * @class InputRKeyPressedEvent
     * @brief Event triggered when the R key is pressed.
     *
     * This event is generated by the display module when the user presses
     * the R key. Typically used for restarting or resetting the current game.
     */
    class InputRKeyPressedEvent : public AInputArcadeEvent {
    public:
        /**
         * @brief Default constructor.
         */
        InputRKeyPressedEvent() = default;

        /**
         * @brief Virtual destructor for proper cleanup.
         */
        ~InputRKeyPressedEvent() override = default;
    };
} // arc

#endif //ARCADE_INPUTRKEYPRESSEDEVENT_HPP
