//
// Created by user on 3/24/26.
//

#ifndef ARCADE_INPUTENTERKEYPRESSEDEVENT_HPP
#define ARCADE_INPUTENTERKEYPRESSEDEVENT_HPP
#include "../../Shared_Abstracts/AInputArcadeEvent.hpp"

namespace arc {
    /**
     * @class InputEnterKeyPressedEvent
     * @brief Event triggered when the Enter/Return key is pressed.
     *
     * This event is generated by the display module when the user presses
     * the Enter key. Typically used for menu selection or confirming actions.
     */
    class InputEnterKeyPressedEvent: public AInputArcadeEvent {
    public:
        /**
         * @brief Default constructor.
         */
        InputEnterKeyPressedEvent()  = default;

        /**
         * @brief Virtual destructor for proper cleanup.
         */
        ~InputEnterKeyPressedEvent() override = default;
    };
} // arc

#endif //ARCADE_INPUTENTERKEYPRESSEDEVENT_HPP
