//
// Created by user on 4/7/26.
//

#ifndef ARCADE_INPUTMOUSERIGHTCLICKEVENT_HPP
#define ARCADE_INPUTMOUSERIGHTCLICKEVENT_HPP
#include "../../Shared_Abstracts/AInputArcadeEvent.hpp"

namespace arc {
    /**
     * @class InputMouseRightClickEvent
     * @brief Event triggered when the right mouse button is clicked.
     *
     * This event is generated by the display module when the user clicks
     * the right mouse button. Contains the mouse coordinates at the time of the click.
     */
    class InputMouseRightClickEvent : public AInputArcadeEvent {
    private:
        /**
         * @brief X coordinate of the mouse click.
         */
        int _x;

        /**
         * @brief Y coordinate of the mouse click.
         */
        int _y;
    public:
        /**
         * @brief Construct a mouse right-click event with coordinates.
         * @param x X coordinate of the click
         * @param y Y coordinate of the click
         */
        InputMouseRightClickEvent(int x, int y) : _x(x), _y(y) {}

        /**
         * @brief Virtual destructor for proper cleanup.
         */
        ~InputMouseRightClickEvent() override = default;

        /**
         * @brief Get the X coordinate of the click.
         * @return int X coordinate in screen space
         */
        int getX() const { return _x; }

        /**
         * @brief Get the Y coordinate of the click.
         * @return int Y coordinate in screen space
         */
        int getY() const { return _y; }
    };

} // arc

#endif //ARCADE_INPUTMOUSERIGHTCLICKEVENT_HPP
