//
// Created by user on 3/24/26.
//

#ifndef ARCADE_INPUTBACKSPACEKEYPRESSEDEVENT_HPP
#define ARCADE_INPUTBACKSPACEKEYPRESSEDEVENT_HPP
#include "../../Shared_Abstracts/AInputArcadeEvent.hpp"

namespace arc {
    /**
     * @class InputBackspaceKeyPressedEvent
     * @brief Event triggered when the Backspace key is pressed.
     *
     * This event is generated by the display module when the user presses
     * the Backspace key. Typically used for text input deletion or menu navigation.
     */
    class InputBackspaceKeyPressedEvent: public AInputArcadeEvent {
    public:
        /**
         * @brief Default constructor.
         */
        InputBackspaceKeyPressedEvent()  = default;

        /**
         * @brief Virtual destructor for proper cleanup.
         */
        ~InputBackspaceKeyPressedEvent() override = default;
    };
} // arc

#endif //ARCADE_INPUTBACKSPACEKEYPRESSEDEVENT_HPP
