//
// Created by user on 3/24/26.
//

#ifndef ARCADE_INPUTTABKEYPRESSEDEVENT_HPP
#define ARCADE_INPUTTABKEYPRESSEDEVENT_HPP
#include "../../Shared_Abstracts/AInputArcadeEvent.hpp"

namespace arc {
    /**
     * @class InputTabKeyPressedEvent
     * @brief Event triggered when the Tab key is pressed.
     *
     * This event is generated by the display module when the user presses
     * the Tab key. Typically used for menu navigation or cycling through selections.
     */
    class InputTabKeyPressedEvent: public AInputArcadeEvent {
    public:
        /**
         * @brief Default constructor.
         */
        InputTabKeyPressedEvent()  = default;

        /**
         * @brief Virtual destructor for proper cleanup.
         */
        ~InputTabKeyPressedEvent() override = default;
    };
} // arc

#endif //ARCADE_INPUTTABKEYPRESSEDEVENT_HPP