//
// Created by user on 3/17/26.
//

#ifndef ARCADE_AGAMEARCADEEVENT_HPP
#define ARCADE_AGAMEARCADEEVENT_HPP
#include "../Shared_Interfaces/IArcadeEvent.hpp"

namespace arc {
    /**
     * @class AGameArcadeEvent
     * @brief Abstract base class for game-related events.
     *
     * Serves as a base class for events that are generated by game logic
     * (as opposed to input events). Examples might include game state changes,
     * collectible pickups, enemy spawns, etc.
     */
    class AGameArcadeEvent : public IArcadeEvent {
    public:
        /**
         * @brief Virtual destructor for proper cleanup of derived classes.
         */
        ~AGameArcadeEvent() override = default;
    };
} // arc

#endif //ARCADE_AGAMEARCADEEVENT_HPP