//
// Created by user on 3/17/26.
//

#ifndef ARCADE_AINPUTARCADEEVENT_HPP
#define ARCADE_AINPUTARCADEEVENT_HPP
#include "../Shared_Interfaces/IArcadeEvent.hpp"


namespace arc {
    /**
     * @class AInputArcadeEvent
     * @brief Abstract base class for input-related events.
     *
     * Serves as a base class for all events generated by user input
     * (keyboard, mouse, joystick, etc). All input event types should
     * inherit from this class.
     */
    class AInputArcadeEvent : public IArcadeEvent {
    };
} // arc

#endif //ARCADE_AINPUTARCADEEVENT_HPP